version: '3.8'

services:
  aerospike:
    image: aerospike/aerospike-server
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - aerospike_data:/opt/aerospike/data

volumes:
  aerospike_data: